### PR TITLE
Feature/bring upstream changes

### PR DESCRIPTION
**Pull request by NachoJusticia**
@crispamares here I put a summary of changes comming from upstream (version blueprintjs/core@3.7.0).

### Main changes:
- Finally our Palantir friends decided to update the Spinner component, so maybe we can give it another opportunity (https://github.com/palantir/blueprint/pull/2970, https://github.com/graphext/blueprint/commit/93513d2799ce18b9c64904cbbdf79681fcde2590) 👍.
Anyhow, I think it does not includes performance changes but just makes the spinner fits the image frame... 
- Minor feature changes in Table that could be of our interest: https://github.com/palantir/blueprint/pull/2988
- New icons added

### CODE REVIEW

**Comment by NachoJusticia** [comment]
I would squash these changes into a single commit

**Comment by crispamares** [comment]
Have you bring already released changes or are you getting them from deploy? 
We should be following only reseases as we use uptstream javascripts in graphext.

I'm fine with the changes.

**Comment by NachoJusticia** [comment]
I brought those changes from `develop` upstream branch which is the default one and where all PRs point to. Version 3.7.0 was published 5 days ago: https://www.npmjs.com/package/@blueprintjs/core

**Comment by crispamares** [comment]
So this PR merge commits that are newer than `3.7.0`? That could cause us problems, where the CSS is more modern than the javascript.

**Comment by NachoJusticia** [comment]
@crispamares see https://github.com/graphext/graphext/pull/165
We should accept both

**Comment by NachoJusticia** [comment]
@crispamares  we won't have problems because these are the changes after published version:
- https://github.com/palantir/blueprint/pull/3007: just affects navigator in `docs package`.
- https://github.com/palantir/blueprint/pull/3006: affects icons in `docs package` and also rename one icon in `icons package` (see https://github.com/palantir/blueprint/pull/3006/files#diff-d73d11510802935431ea7caff3c72323).

Then, there aren't changes in the packages we are using: `core` and `select`.

**Pull request merged**
