### PR TITLE
Tag input tags should show a box-shadow

### PR DESCRIPTION
**Pull request by NachoJusticia**
https://graphext.atlassian.net/browse/GRAPH-1006

captura de pantalla 2018-09-14 a las 10 47 22

As there is no scss variables for that I have had to update styles in overwrites.scss.
See https://github.com/graphext/blueprint/blob/graphext/packages/core/src/components/tag-input/_tag-input.scss#L52

### CODE REVIEW

**Comment by NachoJusticia** [comment]
The only problem I see here is that I haven't been able to customize this component just for dark theme but for both light and dark themes... Could you have a look at that @crispamares ?
Thanks!!

**Comment by NachoJusticia** [comment]
I will focus in icons in other PR

**Comment by crispamares** [comment]
I don't mind about light theme... if we add `.black ` as a prefix should be inly aplied to dark theme

**Comment by cristinatraba** [comment]
The x button on the right should not actually look like a button as it normally is represented as an icon filled with the action blue color. 
Also if I remember correctly the icon featured is a dropdown-arrow instead of a cross.

**Comment by NachoJusticia** [comment]
You are right @cristinatraba , but in this PR just adds a box-shadow to tag input "tags", so please focus on that.
I have other jiras to do the things you propose 👍

**Pull request merged**
